### PR TITLE
🔧 #221 Add B3 propagator

### PR DESCRIPTION
**Pull request by gernest**
Followup to #221

### CODE REVIEW

**Comment by gernest** [comment]
@roma-glushko any ideas on the ci failure?

**Comment by roma-glushko** [comment]
@gernest 

> any ideas on the ci failure?

yes, I do, webhook URL was not passed correctly (empty) for your PRs for some reason:



Ignore it for now, I will be investigating why this is a case

**Comment by roma-glushko** [comment]
GH actions don't share secrets with forks https://github.com/orgs/community/discussions/26163 bummer. This makes implementing notifications more challenging 😌

**Comment by roma-glushko** [comment]
@gernest I have changed the trigger for that action in https://github.com/EinStack/glide/pull/244 Could you please pull that change and see if that makes any difference? 🙏

**Comment by gernest** [comment]
@roma-glushko I pulled the changes PTAL

**Review by roma-glushko — APPROVED** [review]
This is great. Thank you!

**Pull request merged**
