### PR TITLE
🐛 #186: update timeouts per example in time package

### PR DESCRIPTION
**Pull request by mkrueger12**
- changed defaultTimeout, readTimeout, writeTimeout, and idleTimeout to remove multiplication bug

### CODE REVIEW

**Comment by roma-glushko** [comment]
This is interesting 👀 

`10 * time.Second` should be a valid Golang way to define 10 sec interval, let's say. I'm wondering what sort of problem that has caused 🤔

**Comment by mkrueger12** [comment]
@roma-glushko I noticed the timeouts we're 10,000,000,000 in the router config. Not sure if that was seconds or ms but the math still doesn't align to 10s

**Comment by roma-glushko** [comment]
@mkrueger12 My guess It's really 10s but it's just rendered somewhere in micro or nanoseconds which might be confusing. Can you make me a screenshot where you saw that?

**Comment by mkrueger12** [comment]
image

**Comment by roma-glushko** [comment]
Okay, I see. Yes, that's just a confusing way to output that value. The value itself should be fine.
Need to play with swaggertype/JSON to see if it helps to improve the format of `Duration`s:
https://github.com/EinStack/glide/blob/f76eb86918834eba01624698483579ccb5b9fe42/pkg/routers/retry/config.go#L8

**Comment by roma-glushko** [comment]
Gonna close this PR in favour of https://github.com/EinStack/glide/pull/202. Thanks!

**Pull request closed without merging**
